### ISSUE TITLE
resume.js:3 Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by andrewjkerr** [swamphacks/2017Boilerplate#25]
There's a JavaScript error when visiting `http://2017.swamphacks.com`. This is caused by there only being one element in the array when using `window.location.href.split(/[&#]/)`.

```javascript
window.location.href.split(/[&#]/)
// => ["http://2017.swamphacks.com/"]
```

I'll submit a PR to fix this issue in a second. :)

**Comment by brownac** [comment]
This was caused by an unnecessary script tag in index.html; I went ahead and removed it.  Thanks!

**Comment by andrewjkerr** [comment]
@brownac this issue still persists after MLH sign-in on Safari:

![screenshot 2016-11-17 00 47 10](https://cloud.githubusercontent.com/assets/1739462/20377713/64eb20fa-ac5f-11e6-81a5-9a111823d64f.png)

I _think_ there must be something wonky with the MLH callback if this is happening. But, anyway, the PR I opened will take care of this issue across all of the pages: https://github.com/swamphacks/2017Boilerplate/pull/26. :)

**Comment by brownac** [comment]
merged! seems that the callback just doesn't work on safari though. which is funny because it worked in testing.

**Comment by andrewjkerr** [comment]
Yeah, I don't see a reason why it wouldn't work on Safari...

If it's a confirmed issue on the MLH side of things, y'all should reach out to them and see if they can fix it. :)
